<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7KRSIhM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7KRSIhM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7KRSIhM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7KRSIhM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7KRSIhM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7KRSIhM',
    'container.build_id' => '22edbec8',
    'container.build_time' => 1564498296,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7KRSIhM');
