<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5VTiCf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5VTiCf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ5VTiCf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ5VTiCf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ5VTiCf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J5VTiCf',
    'container.build_id' => '0febca94',
    'container.build_time' => 1564489616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5VTiCf');
