<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMQLBJyg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMQLBJyg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMQLBJyg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMQLBJyg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMQLBJyg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MQLBJyg',
    'container.build_id' => '107939df',
    'container.build_time' => 1564507593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMQLBJyg');
